var = input('digite algo: ')
print(type(var))
print('Só tem espaço? ' ,var.isspace())
print('É um número? ' ,var.isnumeric())
print('Possui apenas letras? ' ,var.isalpha())
print('É alfanumérico? ' ,var.isalnum())
print('Está em Maiúsculo? ' ,var.isupper())
print('Está em minúsculo? ' ,var.islower())
print('Inicia com maiúscula? ' ,var.istitle())
